server:
  port: 8081
  servlet:
    context-path: /quartz-project
spring:
  profiles:
    active: @profileActive@
  application:
    name: quartz-project

logging:
  config: classpath:log4j2.xml









